# Define the workspace structure for the PNPM monorepo

packages:
  # Frontend Next.js app
  - 'frontend'
  # Backend NestJS app
  - 'backend'
  # Shared utilities package
  - 'packages/*'

# Dependencies that should be ignored during hoisting
# This helps avoid version conflicts in a monorepo

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
  - sharp
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
