packages:
  - packages/*
  - frontend
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
  - sharp
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@tailwindcss/oxide'
  - msw
  - sharp
  - unrs-resolver
