packages:
  - frontend
  - backend
  - packages/*
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - nx
  - sharp
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
